// ColorSheet.cpp : implementation file
//

#include "stdafx.h"
#include "OnStation.h"
#include "ColorSheet.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CColorSheet

IMPLEMENT_DYNAMIC(CColorSheet, CPropertySheet)

//The warning generated by this code is OK because we do not use the
//this pointer until the OnInitDialog in the base members.  -TVI
CColorSheet::CColorSheet(UINT nIDCaption,int iStartColorScheme,CWnd* pParentWnd, UINT iSelectPage)
:CPropertySheet(nIDCaption, pParentWnd, iSelectPage),m_AgePage(this),m_DepthPage(this)
{
	AddPage(&m_AgePage);
	AddPage(&m_DepthPage);
	if (iStartColorScheme==0)
	{
		SetActivePage(&m_AgePage);
	}
	else
	{
		SetActivePage(&m_DepthPage);
	}
	m_iRecommendedColorSchemeIndex=COLORSCHEME_AGE;
}

CColorSheet::~CColorSheet()
{
}


BEGIN_MESSAGE_MAP(CColorSheet, CPropertySheet)
	//{{AFX_MSG_MAP(CColorSheet)
		// NOTE - the ClassWizard will add and remove mapping macros here.
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CColorSheet message handlers
BOOL CColorSheet::IsDirty()
{
	return m_AgePage.IsDirty() || m_DepthPage.IsDirty();
}