//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by C:\Projects\CaveSurvey\OnStation\res\OnStation.rc
//
#define ID_EDIT_SELECTED                0
#define IDS_QUERYRESULTS                1
#define IDS_CAVEDIVEFLAGCHANGING        2
#define IDD_ABOUTBOX                    100
#define IDC_EDITSTATION                 101
#define IDC_EDIT1                       101
#define IDC_TAPENAME                    102
#define IDC_NAME2                       102
#define IDC_GRIDWIDTH                   102
#define IDD_EDITSURVEY                  103
#define IDC_COMPASS1NAME                103
#define IDC_NAME3                       103
#define IDC_NAME4                       104
#define IDC_NAME5                       105
#define IDC_NAME6                       106
#define IDD_SMAPSIN                     106
#define IDB_LIGHTBULB                   107
#define IDB_XMOVER                      108
#define IDD_COLORS                      108
#define IDB_YMOVER                      109
#define IDC_DRAGDROP                    109
#define IDC_NEXTTIP                     110
#define IDC_DRAGDROPBAD                 110
#define IDD_TIP                         111
#define IDD_FINDSTATION                 114
#define IDD_SEARCHRESULT                115
#define IDD_MULTIPLEFIND                116
#define IDD_NEWFOLDER                   117
#define CG_IDS_DIDYOUKNOW               118
#define IDD_PREVIEWPAGE                 119
#define IDD_GRIDPAGE                    120
#define IDD_SUMMARYPAGE                 121
#define IDD_SURFACESIZEPAGE             122
#define IDD_PEOPLEPAGE                  123
#define IDD_INSTRUMENTPAGE              124
#define IDD_SURFACEALTITUDES            125
#define IDD_SURFACEPREVIEW              126
#define IDD_FIXEDPOINTS                 127
#define IDD_TIEINEDIT                   128
#define IDD_EDITFIXEDPOINT              128
#define IDR_ONSTATTYPE                  129
#define IDR_MAINFRAME                   130
#define IDB_MAINFRAMEBITMAP             131
#define IDS_STRING131                   131
#define IDS_BADWALLFORMAT               131
#define IDD_DEPTHCOLORS                 132
#define IDC_EDITSURVEY                  132
#define IDD_AGECOLORS                   133
#define IDB_BMFOLDERS                   134
#define IDD_PREFERENCES                 134
#define IDB_TITLEIMAGE                  135
#define IDD_AGECOLORHELPERDIALOG        135
#define IDB_BMSURVEYS                   136
#define IDD_PAGESETUP                   136
#define IDC_DATE                        136
#define IDD_PAGELAYOUT                  136
#define IDC_DATEYEAR                    136
#define IDD_ADDTIEIN                    137
#define CG_IDS_FILE_ABSENT              138
#define IDC_DELETELEG                   139
#define IDD_PRINTSURVEYDATA             139
#define IDD_SAVEFORMATTEDTEXTFILE       139
#define CG_IDP_FILE_CORRUPT             140
#define IDD_IMPORTTYPE                  141
#define IDS_COMMENTS                    141
#define IDD_IMPORTERROR                 142
#define IDD_EDITAGECOLOR                143
#define IDR_RULERMENU                   144
#define IDD_NOTESPAGE                   145
#define IDD_FOLDERINFO                  146
#define IDD_SETEXACTVIEW                147
#define IDD_EDITSETTINGSPAGE            148
#define IDD_DEPTHCOLORHELPERDIALOG      149
#define IDD_VIEWANGLE                   150
#define IDD_VIEWCENTER                  151
#define IDB_BITMAPGLASS                 152
#define IDR_COMPASSMENU                 153
#define IDC_SURVEYLIST                  154
#define IDD_PASSAGEVIEWDIALOG           154
#define IDD_RENAMECOLORSCHEME           155
#define IDD_VIEWSCALE                   156
#define IDD_CENTERSTATION               157
#define IDR_VIEWPORTMENU                158
#define IDD_MULTIPLEERROR               159
#define IDR_RULERMENUINCHES             159
#define IDD_LOOPCLOSUREWAIT             160
#define IDD_TIPOFTHEDAY                 161
#define IDD_ABOUTBOXCREDITS             162
#define IDD_ABOUTBOXSUMMARY             163
#define IDD_ORPHANDIALOG                164
#define IDD_ALIASFORSHORTCUTS           165
#define IDD_ALIASFORHOWDOI              166
#define IDD_ALIASFORSUPPORT             167
#define IDD_FOLDERINFOBYVIEW            168
#define CG_IDS_TIPOFTHEDAYHELP          169
#define IDB_SPLASH                      170
#define IDC_COMMENTS                    173
#define IDC_SURVEYNAME                  174
#define IDC_DECLINATION                 175
#define IDC_CLINO_STD_ERROR             177
#define IDC_CHECKMETRIC                 185
#define IDD_COMMENTDIALOG               185
#define IDC_CHECKUPDOWN                 186
#define IDC_CHECKLEFTRIGHT              187
#define IDD_BOOKMARKS                   187
#define IDD_TITLEPAGESETUP              188
#define IDC_CREATE                      189
#define IDB_DIDYOUKNOW                  190
#define IDD_HOWMANYDEPTHINTERVALS       191
#define IDB_SPINBMP                     192
#define IDB_TILTBMP                     193
#define IDC_TDF1                        195
#define IDD_BILLBOARD                   195
#define IDD_TIPOFTHEDAY16               196
#define IDC_TDF3                        197
#define IDD_QUERYDIALOG                 197
#define IDC_TDF4                        198
#define IDD_SEARCHCOMMENTSDIALOG        198
#define IDC_TDS1                        199
#define IDD_PASSAGE_OPTIONS             199
#define IDD_SEARCHSURVEYS               200
#define IDD_ABOUTBOXWWW                 201
#define IDC_TDS4                        202
#define IDD_OVERALLDATAVIEW             202
#define IDC_VIEWPORT                    203
#define IDD_ABOUTBOXWEB                 203
#define IDR_SURVEYTREEMENU              206
#define IDB_BITMAPPIN                   207
#define IDB_BITMAPPINROOT               208
#define IDC_SMAPSINFO                   209
#define IDB_SURFACEFOLDERROOT           209
#define IDB_SURFACEFOLDER               210
#define IDR_FULLSCREENTOOLBAR           211
#define IDB_BITMAPPINONSCREEN           212
#define IDB_BITMAPSEARCHFOUND           213
#define IDB_QUESTIONBRUSH               214
#define IDD_DISTANCEBETWEENSTATIONS     215
#define IDB_BITMAPPINSEARCH             215
#define IDC_STATICTRANSLATE             216
#define IDD_DEBUGSTATIONLINKS           220
#define IDD_BLUNDERS                    222
#define IDC_BUTTONADDONE                267
#define IDC_APPLY_NOW                   267
#define IDC_DEFAULTS                    267
#define IDC_INFO                        267
#define IDC_SURFACE                     267
#define IDC_ADD                         267
#define IDC_FIXTHISPOINT                267
#define IDC_CHECK_SURFACE_SURVEY        272
#define IDC_BUTTONCENTER                276
#define IDC_STATIC_Z                    279
#define IDC_STATIC_X                    280
#define IDC_STATIC_Y                    281
#define IDC_STNLIST                     282
#define IDC_BUTTONFOLDER                284
#define IDC_BUTTONDEFAULTS              285
#define IDC_COLORSLOT                   288
#define IDC_COLOR1                      291
#define IDC_SYSTEM                      298
#define IDC_CHECKBACKSIGHTS             300
#define IDC_NAME1                       301
#define IDC_JOB1                        302
#define IDC_JOB2                        303
#define IDC_CLINO1NAME                  304
#define IDC_JOB3                        304
#define IDC_COMPASS2NAME                305
#define IDC_JOB4                        305
#define IDC_CLINO2NAME                  306
#define IDC_JOB5                        306
#define IDC_TAPEFIX                     307
#define IDC_JOB6                        307
#define IDC_COMPASS1FIX                 308
#define IDC_CLINO1FIX                   309
#define IDC_TOP                         309
#define IDC_BOTTOM                      309
#define IDC_COMPASS2FIX                 310
#define IDC_LEFT                        310
#define IDC_CLINO2FIX                   311
#define IDC_HEIGHT                      311
#define IDC_WIDTH                       312
#define IDC_CELLSIZE                    313
#define IDC_TAPE_STD_ERROR              317
#define IDC_COMPASS_STD_ERROR           318
#define IDC_STATIONLIST                 323
#define IDC_EDIT                        324
#define IDC_REMOVE                      325
#define IDC_STATIONTEXT                 326
#define IDC_EDITXPOS                    328
#define IDC_EDITYPOS                    329
#define IDC_EDITZPOS                    330
#define IDC_STATICZ                     331
#define IDC_ZCHECK                      332
#define IDC_STATIONNAME                 333
#define IDC_NEWCOLORSLOT                335
#define IDC_DEPTHDRAW                   338
#define IDC_EDITINCREMENTS              339
#define IDC_STATICTITLE                 340
#define IDC_EDITSTARTDEPTH              340
#define IDC_STATICWARNING               341
#define IDC_STATICAUTHOR                342
#define IDC_STATICPICTURE               344
#define IDC_EDITDATE                    345
#define IDC_BUTTONREMOVE                346
#define IDC_AGELIST                     347
#define IDC_CHECKINCLUDESCALE           348
#define IDC_CHECKINCLUDENORTHARROW      349
#define IDC_SCALECOMBO                  351
#define IDC_HEADER                      356
#define IDC_SHOTS                       357
#define IDC_LEGTOTALS                   358
#define IDC_SYSTEMTOTALS                359
#define IDC_GRIDNORTH                   362
#define IDC_SURFACECELLSIZE             363
#define IDC_DESCRIPTION                 364
#define IDC_COLUMNS                     367
#define IDC_SMAPS                       368
#define IDC_SMAPSSEF                    369
#define IDC_SMAPSSINGLE                 370
#define IDC_BADLINE                     375
#define IDC_EXPECTING                   376
#define IDC_GOT                         377
#define IDC_EDIT_ROTATEZ                383
#define IDC_EDITROTATEX                 384
#define IDC_APPLY                       386
#define IDC_COMBOOVERLAP                387
#define IDC_NOTESLIST                   388
#define IDC_EDITNOTES                   389
#define IDC_CHECK_THICKLINES            390
#define IDC_FOLDERNAME                  392
#define IDC_CAVESURVEYSSHOTS            393
#define IDC_CAVELENGTH                  394
#define IDC_HIGHEST                     395
#define IDC_DEEPEST                     396
#define IDC_SURFACESURVEYSSHOTS         397
#define IDC_SURFACELENGTH               398
#define IDC_COPY                        402
#define IDC_PASTE                       403
#define IDC_EDITUD                      404
#define IDC_EDITEW                      407
#define IDC_EDITNS                      408
#define IDC_SCALESIZE                   409
#define IDC_CENTERNAME                  410
#define IDC_LISTCOLUMNS                 413
#define IDC_MOVEDOWN                    414
#define IDC_MOVEUP                      415
#define IDC_COMBO1                      1000
#define IDC_CHECK1                      1000
#define IDC_BULB                        1000
#define IDC_CHECK2                      1001
#define IDC_STARTUP                     1001
#define IDC_CHECK3                      1002
#define IDC_CHECK4                      1003
#define IDC_CHECK5                      1004
#define IDC_TIPSTRING                   1004
#define IDC_CHECK6                      1005
#define IDC_CHECK7                      1006
#define IDC_WIZARD                      1006
#define IDC_STARTINGDATE                1007
#define IDC_YEARS                       1008
#define IDC_NUMINTERVALS                1009
#define IDC_STARTINGDEPTH               1011
#define IDC_DEPTH                       1012
#define IDC_ELEVUP                      1013
#define IDC_ELEVDOWN                    1014
#define IDC_BUTTONROTLEFT               1015
#define IDC_BUTTONROTRIGHT              1016
#define IDC_EDITELEVATE                 1017
#define IDC_EDITROTATE                  1018
#define IDC_ZPAN                        1019
#define IDC_XPAN                        1020
#define IDC_YPAN                        1021
#define IDC_BUTTON1                     1022
#define IDC_RADIO1                      1024
#define IDC_RADIO2                      1025
#define IDC_AUTONUMBER                  1025
#define IDC_RADIO3                      1026
#define IDC_AUTONUMBER2                 1026
#define IDC_AUTOSIZE                    1026
#define IDC_RADIO4                      1027
#define IDC_RADIO5                      1028
#define IDC_RADIO6                      1029
#define IDC_RADIO7                      1030
#define IDC_EVENSPLIT                   1032
#define IDC_RENAMECOLOR                 1033
#define IDC_STATIC1                     1035
#define IDC_STATIC2                     1036
#define IDC_NUMSURVEYS                  1037
#define IDC_NUMSHOTS                    1038
#define IDC_TOTALLENGTH                 1039
#define IDC_HIGHESTPOINT                1040
#define IDC_DEEPESTPOINT                1041
#define IDC_HIGHESTNAME                 1042
#define IDC_HORIZONTALLENGTH            1042
#define IDC_DEEPESTNAME                 1043
#define IDC_TOTALDEPTH                  1044
#define IDC_BUTTONRAINBOW               1044
#define IDC_NUMSURFACESURVEYS           1045
#define IDC_STATIC3                     1045
#define IDC_NUMSURFACESHOTS             1046
#define IDC_TOTALSURFACELENGTH          1047
#define IDC_PROGRESS2                   1047
#define IDC_TIPTEXT                     1048
#define IDC_DIDYOUKNOW                  1050
#define IDC_STATICDEVELOPER             1051
#define IDC_STATICLOOPS                 1052
#define IDC_STATICWEBPAGE               1053
#define IDC_LIST1                       1054
#define IDC_BUTTON2                     1055
#define IDC_ADDCOMMENT                  1057
#define IDC_DELETECOMMENT               1058
#define IDC_COMMENTLIST                 1059
#define IDC_EDIT2                       1060
#define IDC_GOTO                        1061
#define IDC_EDIT6                       1061
#define IDC_DELETE                      1062
#define IDC_STATICPANNING               1063
#define IDC_STATICROTATION              1064
#define IDC_BOOKMARKLIST                1065
#define IDC_BOOKMARKCOMBO               1066
#define IDC_CHECKSIDESCALE              1067
#define IDC_EDITTITLE                   1068
#define IDC_EDIT3                       1069
#define IDC_EDIT4                       1070
#define IDC_EDIT5                       1071
#define IDC_STATICX                     1079
#define IDC_STATICY                     1080
#define IDC_GRIDHEIGHT                  1081
#define IDC_STATICINTERVAL              1082
#define IDC_STATICSTARTDEPTH            1083
#define IDC_STATICTEXT                  1087
#define IDC_COLORSTATIC                 1088
#define IDC_PLACETAG                    1089
#define IDC_COLORTOSHOT                 1090
#define IDC_COLORFROMSHOT               1091
#define IDC_DISPLAYRESULTS              1092
#define IDC_COMBO2                      1093
#define IDC_SURFACEALTITUDEGRID         1094
#define IDC_STATICANDTEXT               1095
#define IDC_GRID1                       1096
#define IDC_EURODEGREESCHECK            1097
#define IDC_CUT                         1098
#define IDC_SOURCECODE                  1099
#define IDC_BUGLIST                     1100
#define IDC_MAINPAGE                    1101
#define IDC_COMPASS2TEXT                1105
#define IDC_CLINO2TEXT                  1106
#define IDC_CLINO1TEXT                  1107
#define IDC_CLINO1TEXTA                 1108
#define IDSHOWSURVEYS                   1109
#define IDC_STATICQUERYTEXT             1110
#define IDC_MULTIPLELIGHTS              1113
#define IDC_DATEMONTH                   1115
#define IDC_DATEDAY                     1116
#define IDC_BUTTON3                     1118
#define IDC_BUTTON4                     1119
#define IDC_DISABLELIGHTROTATE          1120
#define IDC_UNDO                        1121
#define IDC_YFROM                       1122
#define IDC_MFROM                       1123
#define IDC_DFROM                       1124
#define IDC_YTO                         1125
#define IDC_CAVEDIVECHECK               1125
#define IDC_MTO                         1126
#define IDC_TOTALALLSURVEYS             1126
#define IDC_DTO                         1127
#define IDC_TOTALNOTEXCLUDED            1127
#define IDC_TOTALEXCLUDED               1128
#define IDC_DATEEDIT1                   1129
#define IDC_DATEEDIT2                   1130
#define IDC_INSERTLINE                  1130
#define IDC_DIVEMETERS                  1131
#define IDC_DEVIATIONS                  1132
#define IDC_BLU_DEV                     1133
#define IDC_BLU_MAX                     1134
#define IDC_BLU_COM                     1135
#define IDC_BLU_TAP                     1136
#define IDC_BLU_CLI                     1137
#define IDC_BLU_DISPLAY                 1138
#define IDC_DATETIMEPICKER1             1182
#define IDS_ONLYDRAGSURVEYSANDFOLDER    10000
#define IDS_INTERNALERRORINLOOPCLOSURE  10001
#define IDS_SMAPSSINGLEISBAD            10002
#define IDS_NOGRIDCONTROL               10002
#define IDS_MISSINGCLOSINGPAREN         10003
#define IDS_ILLEGALANDOR                10004
#define IDS_MISSINGOPENINGPAREN         10005
#define IDS_MISSINGCLOSINGQUOTES        10006
#define IDS_UNABLETOPARSEEXPRESSION     10007
#define IDS_TIEINWASREMOVED             10008
#define IDS_NORENDERMEMORY              10009
#define IDS_MISSINGDATECONTROL          10009
#define IDS_LOOPCLOSUREINTERNALERROR    10010
#define IDS_PASTEFAILED                 10011
#define IDS_DATEFORMATPROBLEM           10013
#define IDS_DATEYEARBAD                 10013
#define IDS_SEARCH                      10013
#define IDS_IMPORTGOESINCURRENT         10014
#define IDS_FILEOPENLATERVERSION        10015
#define IDS_CALCULATESYSTEMINTERNALERROR 10016
#define IDS_ENTERVALIDNUMBER            10017
#define IDS_BACKSIGHTLOSS               10018
#define IDS_NEEDSURVEYNAME              10019
#define IDS_INCOMPLETESHOT              10020
#define IDS_BACKSIGHTMISMATCH           10021
#define IDS_COMPASSMISMATCH             10022
#define IDS_COMPASSRANGE                10023
#define IDS_BADSTATIONNAME              10024
#define IDS_COMPASSRANGEEURO            10025
#define IDS_CLINORANGE                  10026
#define IDS_CLINORANGEEURO              10027
#define IDS_BADSTARTTOFILE              10029
#define IDS_ORPHANEDLISTINVALID         10030
#define IDS_METERLIMIT                  10031
#define IDS_FEETLIMIT                   10032
#define IDS_CANTFINDFIXEDPOINT          10033
#define IDS_INVALIDSTATIONNAME          10034
#define IDS_NOSURVEYORFOLDERSELECTED    10035
#define IDS_NOOPENCLIPBOARD             10036
#define IDS_BLUNDERLISTINVALID          10036
#define IDS_GENERALMEMORYERROR          10037
#define IDS_NOFORMATONCLIPBOARD         10038
#define IDS_FILEERRORFORMATSTRING       10039
#define IDS_OLDFORMATUSETRANSLATOR      10039
#define IDS_FILEIMPORTNOTSUCCESSFUL     10040
#define IDS_BADLINEFORMAT               10040
#define IDS_NOGOODLINES                 10041
#define IDS_BADLINEOVERRUN              10041
#define IDS_TOOBIGFOLDER                10042
#define IDS_ENDOFFILEERROR              10042
#define IDS_DELETEWARNING               10043
#define IDS_SEARCHNOLONGERVALID         10044
#define IDS_MAJORSURFACEDATAERROR       10045
#define IDS_EURODEGREESCHANGED          10045
#define IDS_EVENGRID                    10046
#define IDS_FULLSCREEN                  10046
#define IDS_CHANGEDLOCATIONANDSQUARESIZE 10047
#define IDS_DUPLICATEFIXEDPOINT         10047
#define IDS_CHANGEDGRIDNOMOVE           10048
#define IDS_DISABLEDLEGSCREWTHISUP      10048
#define IDS_CHANGEDLOCATION             10049
#define IDS_HELPTHROUGHBROWSER          10049
#define IDS_CHANGEDLOCATIONANDSIZE      10050
#define IDS_SELECTFILLAREA              10051
#define IDS_FILLNEEDSFROMANDTO          10052
#define IDS_BADFILLPATTERN              10053
#define IDS_UNABLETODUMPFORMATTEDTEXT   10054
#define IDS_SAVEFORMATTEDTEXTFAILEDUNKNOWN 10055
#define IDS_HIDE                        10056
#define IDS_DISABLE                     10057
#define IDS_COLORSCHEMENAME             10058
#define IDS_FIXEDPOINTROOTNAME          10059
#define IDS_INCOMPLETESHOTDEPTH         10060
#define IDS_FROMSTATION                 10061
#define IDS_TOSTATION                   10062
#define IDS_COMPASS                     10063
#define IDS_COMPASSBACK                 10064
#define IDS_CLINOMETER                  10065
#define IDS_CLINOMETERBACK              10066
#define IDS_LENGTH                      10067
#define IDS_UP                          10068
#define IDS_DOWN                        10069
#define IDS_LEFT                        10070
#define IDS_RIGHT                       10071
#define IDS_DEPTH                       10072
#define IDS_SURFACEPROPERTYSHEETTITLE   10073
#define IDS_SURFACEFOLDERTITLE          10074
#define IDS_SURVEYEDITSHEETTITLE        10075
#define IDS_COLORSCHEMEHOTKEY           10076
#define IDS_ORPHANFORMAT                10077
#define IDS_DELETELEGWARNING            10078
#define IDS_UNKNOWNSYMBOLFORMAT         10079
#define IDS_BOGUS_LINE_READS            10080
#define IDS_ERRORREADINGFILE            10081
#define IDS_FILEIMPORTFORMAT            10082
#define IDS_LEGNUMBERFORMAT             10083
#define IDS_NUMSUCCESSFULLINES          10084
#define IDS_CLINOTAG                    10084
#define IDS_FOLDERTOTALS                10085
#define IDS_SURVEYTOTALS                10086
#define IDS_CONTAINSNOSHOTS             10087
#define IDS_SUMMARYHEADER               10088
#define IDS_LENGTHTOTAL                 10089
#define IDS_UNTITLED                    10090
#define IDS_DEPTHTAG                    10091
#define IDS_ABOUTONSTATION              10092
#define IDS_FREEFORM                    10093
#define IDS_PROFILE                     10094
#define IDS_MIXED                       10095
#define IDS_PLAN                        10096
#define IDS_STARTDEPTHM                 10097
#define IDS_INTERVALM                   10098
#define IDS_STARTDEPTHFT                10099
#define IDS_INTERVALFT                  10100
#define IDS_STANDARD                    10101
#define IDS_SURVEYROOT                  10102
#define IDS_NORTH                       10103
#define IDS_CONFIGURECOLORS             10104
#define IDS_VALUELIMITSFT               10105
#define IDS_SIZEFTIN                    10106
#define IDS_BADSTATIONSCOUNT            10107
#define IDS_MIXEDDIVEERROR              10107
#define IDS_BEFORE                      10108
#define IDS_ANDLATER                    10109
#define IDS_STOS                        10110
#define IDS_NAMETABDEPTH                10111
#define IDS_XPOS                        10112
#define IDS_YPOS                        10113
#define IDS_ZPOS                        10114
#define IDS_SURVEYNAME                  10115
#define IDS_PERSONNEL                   10116
#define IDS_DESCRIPTION                 10117
#define IDS_QUERYAND                    10118
#define IDS_QUERYOR                     10119
#define IDS_STATIONS                    10120
#define IDS_DATE                        10121
#define IDS_TILTSPINZOOM                10122
#define IDS_XYZ                         10123
#define IDS_2FKM                        10124
#define IDS_1FM                         10125
#define IDS_2FMILES                     10126
#define IDS_1FFT                        10127
#define IDS_2FMCM                       10128
#define IDS_2FFTINCH                    10129
#define IDS_X                           10130
#define IDS_Y                           10131
#define IDS_Z                           10132
#define IDS_TILT                        10133
#define IDS_SPIN                        10134
#define IDS_SAVEFSURVEY                 10135
#define IDS_SAVEFSYSTEM                 10136
#define IDS_SAVEFDESCRIPTION            10137
#define IDS_SAVEFDATE                   10138
#define IDS_SAVEFTECHNICAL              10139
#define IDS_SAVEFMETERS                 10140
#define IDS_SAVEFFEET                   10141
#define IDS_SAVEFDECLINATION            10142
#define IDS_SAVEFNAMEDUTY               10143
#define IDS_SAVEFDIVEHEADING            10144
#define IDS_SAVEFLEGHEADING             10145
#define IDS_SAVEFTOTALS                 10146
#define IDS_SAVEFNOSHOTS                10147
#define IDS_SAVEFTOTALS2                10148
#define IDS_SAVEFTOTALS3                10149
#define IDS_RESETALLSURFACEDATA         10150
#define IDS_REMOVEALLFIXEDPOINTS        10151
#define IDS_COLORSCHEMEAGE              10152
#define IDS_COLORSCHEMEDEPTH            10153
#define IDS_DATEMONTHBAD                10155
#define IDS_SURFACECHANGEDSUGGESTPASTE  10155
#define IDS_DATEDAYBAD                  10156
#define IDS_NO_IMPORT_EXE               10157
#define IDS_NOBROWSER                   10158
#define IDS_NOMATCHONSEARCH             10159
#define IDS_BETWEEN                     10160
#define IDS_BEFORE2                     10161
#define IDS_AFTER                       10162
#define IDS_ENTERVALIDSTATIONNAME       10163
#define IDS_DISTANCERESULT              10164
#define IDS_SOUTH                       10165
#define IDS_EAST                        10166
#define IDS_WEST                        10167
#define IDS_LOCATION                    10168
#define IDS_QUERYNOMATCHES              10169
#define IDS_UNEXPECTEDTOKEN             10170
#define IDS_SCOPINGERROR                10171
#define IDS_UNEXPECTEDTOKENBEGIN        10171
#define IDS_MISMATCHEDEND               10172
#define IDS_WRONGEND                    10173
#define IDS_LINETOOLONG                 10174
#define IDS_BADSHOTFORMAT               10175
#define IDS_BADFORMATSTRING             10176
#define IDS_UNABLETOOPENFILE            10177
#define IDS_UNEXPECTEDTOKENEND          10178
#define ID_EDIT_SURVEY                  32769
#define ID_FILE_IMPORT                  32771
#define ID_VIEW_RULER                   32772
#define ID_VIEW_VIEWTABS                32773
#define ID_EDIT_CONFIGURECOLORS         32774
#define ID_VIEW_TOOLBARS                32775
#define ID_RULER_MAXIMUMZOOM            32776
#define ID_RULER_EXPAND50               32777
#define ID_RULER_SHRINK50               32778
#define ID_RULER_5MCM                   32779
#define ID_RULER_10MCM                  32780
#define ID_RULER_25MCM                  32781
#define ID_RULER_50MCM                  32782
#define ID_VIEW_SURFACEOVERLAY          32783
#define ID_RULER_100MCM                 32783
#define ID_RULER_MAXIMUMSHRINK          32788
#define ID_MOVEMENT_PLANVIEW            32794
#define ID_RULER_500MCM                 32794
#define ID_MOVEMENT_PROFILEVIEW         32795
#define ID_RULER_1000MCM                32795
#define ID_MOVEMENT_MIXEDVIEW           32796
#define ID_MOVEMENT_FREEFORMVIEW        32797
#define ID_VIEW_PASSAGEOPTIONS          32798
#define ID_NORTH                        32799
#define IDS_COLORSCHEMEBLUNDER          32799
#define ID_VIEW_SURFACEANDLOCATIONSURVEYS 32800
#define ID_SOUTH                        32800
#define ID_EAST                         32801
#define ID_EDIT_FINDSTATION             32802
#define ID_WEST                         32802
#define ID_COMPASS_TILTUP45DEGREES      32803
#define ID_TILT0                        32803
#define ID_VIEW_NAMEALL                 32804
#define ID_COMPASS_45DEGREETILT         32804
#define ID_TILT45                       32804
#define ID_VIEW_NAMEJUNCTIONS           32805
#define ID_COMPASS_TILT0SIDEVIEW        32805
#define ID_TILT90                       32805
#define ID_VIEW_NAMENONE                32806
#define ID_COMPASS_TILT45               32806
#define ID_TILT135                      32806
#define ID_EDIT_VIEWCOLORS              32807
#define ID_EDIT_SURFACE                 32808
#define ID_DRAWMODE_AGECOLORING         32809
#define ID_HELP_TECHNICALSUPPORT        32811
#define ID_VIEWPORT_SETEXACTVIEW        32812
#define ID_VIEWPORT_FINDSTATION         32813
#define ID_VIEWPORT_CHANGECOLORING      32814
#define ID_VIEW_CLOSELOOPS              32815
#define ID_VIEWPORT_ZOOMIN              32816
#define ID_FILE_PRINTSURVEYDATA         32817
#define ID_VIEWPORT_ZOOMOUT             32817
#define ID_VIEWPORT_ROTATELEFT          32818
#define ID_HELP_HOWDOI                  32819
#define ID_VIEWPORT_ROTATERIGHT         32819
#define ID_VIEWPORT_TILITFORWARD        32820
#define ID_VIEWPORT_TILTFORWARD         32820
#define ID_DRAWMODE_NORMALCOLORS        32821
#define ID_VIEWPORT_TILTBACK            32821
#define ID_RULER_10FTINCH               32822
#define ID_DRAWMODE_DEPTHCODING         32823
#define ID_RULER_20FTINCH               32823
#define ID_DRAWMODE_PERSPECTIVE         32824
#define ID_RULER_50FTINCH               32824
#define ID_RULER_100FTINCH              32825
#define ID_VIEW_SETEXACTVIEW            32826
#define ID_RULER_500FTINCH              32826
#define ID_RULER_1000FTINCH             32827
#define ID_RULER_5000FTINCH             32828
#define ID_NORTHEAST                    32829
#define ID_SOUTHEAST                    32830
#define ID_SOUTHWEST                    32831
#define ID_NORTHWEST                    32832
#define ID_TILT180                      32833
#define ID_VIEW_NOWALLS                 32834
#define ID_VIEWPORT_NORTH               32834
#define ID_VIEW_CROSSSECTIONSONLY       32835
#define ID_VIEWPORT_EAST                32835
#define ID_VIEW_FULLTUNNELS             32836
#define ID_VIEWPORT_SOUTH               32836
#define ID_VIEWPORT_WEST                32837
#define ID_DRAWMODE_CUSTOMCOLORS        32838
#define ID_DRAWMODE_COLORSCHEME1        32839
#define ID_DRAWMODE_COLORSCHEME2        32840
#define ID_DRAWMODE_COLORSCHEME3        32841
#define ID_DRAWMODE_COLORSCHEME4        32842
#define ID_DRAWMODE_COLORSCHEME5        32843
#define ID_DRAWMODE_COLORSCHEME6        32844
#define ID_DRAWMODE_COLORSCHEME7        32845
#define ID_DRAWMODE_COLORSCHEME8        32846
#define ID_HELP_SUMMARYOFSHORTCUTS      32847
#define ID_HELP_TIPOFTHEDAY             32848
#define ID_EDIT_ORPHANEDSHOTS           32850
#define ID_HELP_CONTENTS                32851
#define ID_VIEW_PREFERENCES             32852
#define ID_ABOUT_ONSTATION              32853
#define ID_VIEW_INFORMATION             32854
#define ID_EDIT_BOOKMARKS               32855
#define ID_FILE_PRINTINGPREFERENCES     32856
#define ID_EDIT_FIXEDPOINTS             32864
#define ID_OPTIONS_MARKFIXEDPOINTS      32865
#define ID_FILE_SENDMAIL                32866
#define ID_VIEW_ZOOMIN                  32868
#define ID_VIEW_ZOOMOut                 32869
#define ID_VIEWPORT_EDITBOOKMARKS       32870
#define ID_OPTIONS_CLOSUREERRORS        32871
#define ID_FILE_EXPORTVRMLFILE          32873
#define ID_EDIT_SEARCHSTATIONCOMMENTS   32874
#define ID_EDIT_FINDSSURVEY             32875
#define ID_EXPORTFORMATTEDTEXT          32877
#define ID_FILE_EXPORTFORMATTEDTEXT     32878
#define ID_SURVEYTREE_NEWSURVEY         32883
#define ID_SURVEYTREE_NEWFOLDER         32884
#define ID_SURVEYTREE_EDITCURRENTITEM   32885
#define ID_SURVEYTREE_DELETECURRENTITEM 32886
#define ID_SURVEYMENU_EDITSURVEY        32887
#define ID_SURVEYMENU_DELETESURVEY      32888
#define ID_EDIT_ADDSURVEY               32890
#define ID_SURVEYMENU_ADDSURVEY         32891
#define ID_SURVEYMENU_ADDFOLDER         32892
#define ID_SURVEYMENU_CUT               32893
#define ID_SURVEYMENU_EDIT_COPY         32894
#define ID_SURVEYMENU_PASTE             32895
#define ID_EDIT_DELETESELECTED          32896
#define ID_EDIT_ADDTIEIN                32898
#define ID_EDIT_ADDFIXEDPOINT           32899
#define ID_EDIT_DELETE                  32900
#define ID_EDIT_ADDFOLDER               32901
#define ID_SURVEYTREE_NEWFIXEDPOINT     32902
#define ID_EDIT_EDIT                    32904
#define ID_VIEW_FULLSCREEN              32905
#define ID_EDIT_PROPERTIES              32906
#define ID_EDIT_ENDQUERY                32907
#define ID_VIEW_FULLSCREEN_ESCKEY       32911
#define ID_VIEWPORT_STARTINGPOSITION    32912
#define ID_SEARCH_SHOWSTATION           32913
#define ID_SURVEYTREE_RAINBOWCOLORSURVEYS 32914
#define ID_VIEW_ANIMATE                 32915
#define ID_VIEW_DISTANCEBETWEENSTATIONS 32916
#define ID_SURVEYTREE_COPY              32917
#define ID_INSERT_FILE                  32918
#define IDS_PT_LINE_PLOT                32919
#define IDS_PT_HEIGHTS                  32920
#define ID_DEBUG_STATIONLINKS           32920
#define IDS_PT_WIDTHS                   32921
#define ID_DRAWING_FONT                 32921
#define IDS_PT_FULL_PASSAGES            32922
#define ID_FILE_EXPORTDXF               32922
#define IDS_PT_CROSS_SECTIONS           32923
#define IDS_PT_PASSAGES_SKINNY          32924
#define IDS_PT_FULL_PASSAGES_SKINNY     32925
#define IDS_CDT_IGNORE_DATES            32926
#define IDS_CDT_BETWEEN                 32927
#define IDS_CDT_BEFORE                  32928
#define IDS_CDT_AFTER                   32929
#define IDS_JOBBOOK                     32930
#define IDS_JOBTAPE                     32931
#define IDS_JOBINSTRUMENTS              32932
#define IDS_JOBRIGGING                  32933
#define IDS_JOBEXPLORATION              32934
#define IDS_FT_SURVEYDATA               32935
#define IDS_FT_RAWCOORDINATES           32936
#define ID_DRAWMODE_BLUNDERCOLOR        32937
#define ID_QUERY_BLUNDERS               32938
#define ID_SHOWREFERENCE_GRID           32939
#define ID_ERRORSLOOPS_LOOPCLOSUREOPTIONS 32940
#define ID_INDICATOR_CLOCKWISE          0xE707
#define ID_INDICATOR_TILT               0xE708
#define ID_INDICATOR_XPAN               0xE709
#define ID_INDICATOR_YPAN               0xE710
#define ID_INDICATOR_ZPAN               0xE711
#define ID_INDICATOR_SCALE              0xE712

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32950
#define _APS_NEXT_CONTROL_VALUE         1183
#define _APS_NEXT_SYMED_VALUE           171
#endif
#endif
